name: 'Comment on PR'
description: '在 PR 或 Issue 上发布评论，支持更新已有评论'

inputs:
  pat-token:
    description: 'GitHub Personal Access Token'
    required: true
  message:
    description: '要发布的评论内容'
    required: true
  update-if-exists:
    description: '如果已有评论则更新（默认 false）'
    required: false
    default: 'false'
  comment-identifier:
    description: '用于识别已有评论的标识文本（用于更新时查找评论）'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Comment on PR or Issue
      if: ${{ inputs.pat-token != '' && (github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)) }}
      continue-on-error: true
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.pat-token }}
        script: |
          const comment = process.env.MESSAGE_CONTENT;
          const shouldUpdate = '${{ inputs.update-if-exists }}' === 'true';
          const identifier = '${{ inputs.comment-identifier }}';
          
          // 获取 issue/PR 编号
          const issueNumber = context.issue?.number || context.payload.issue?.number;
          
          if (!issueNumber) {
            console.log('⚠️ Could not determine issue/PR number');
            return;
          }
          
          console.log(`📝 Commenting on #${issueNumber}`);
          
          try {
            if (shouldUpdate) {
              // 查找已有的评论并更新
              const { data: comments } = await github.rest.issues.listComments({
                issue_number: issueNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              
              // 优先使用 HTML 注释标记查找（最可靠）
              let botComment = comments.find(c => 
                c.user.type === 'Bot' && 
                c.body.includes('<!-- PR_TEST_COMMENT -->')
              );
              
              // 如果没有找到 HTML 注释标记，则使用 identifier（向后兼容）
              if (!botComment && identifier) {
                // 找到所有匹配的评论，选择最早创建的那个（避免多个评论）
                const matchingComments = comments.filter(c => 
                  c.user.type === 'Bot' && 
                  c.body.includes(identifier)
                );
                
                if (matchingComments.length > 0) {
                  // 按创建时间排序，选择最早的那个
                  matchingComments.sort((a, b) => 
                    new Date(a.created_at) - new Date(b.created_at)
                  );
                  botComment = matchingComments[0];
                  
                  // 如果找到多个匹配的评论，记录警告
                  if (matchingComments.length > 1) {
                    console.log(`⚠️ Found ${matchingComments.length} matching comments, updating the earliest one (ID: ${botComment.id})`);
                  }
                }
              }
              
              if (botComment) {
                // 更新已有评论
                await github.rest.issues.updateComment({
                  comment_id: botComment.id,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: comment
                });
                console.log(`✅ Comment updated (ID: ${botComment.id})`);
                return;
              }
            }
            
            // 创建新评论
            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            console.log(`✅ Comment created on #${issueNumber}`);
          } catch (error) {
            console.error('❌ Failed to comment:', error.message);
            if (error.status) {
              console.error(`   Status: ${error.status}`);
            }
            if (error.response?.data) {
              console.error(`   Details: ${JSON.stringify(error.response.data, null, 2)}`);
            }
            throw error;
          }
      env:
        MESSAGE_CONTENT: ${{ inputs.message }}

